### ISSUE TITLE
Set environnent variable at launch

### ISSUE THREAD

**Issue by AntoineKMS** [Alipsa/ride#17]
Hi, 

I was wondering if it would be possible to set some environment variable at Ride startup.

Coming from RStudio, it usually save the "session" with all the variables that have been set when you close the app in a .RData file and load this file at startup.

I don't need something like this, even if it would be usefull in Ride to be able to not forget the environnement when closing Ride. But I see that at launch , there is the '''.Random.seed  c(1L)''' environnement variable being set. 

Is there an easy way to add our own environnement variables to be set at launch and loaded like this '''.Random.seed  c(1L)''' ?

Thank you.

**Comment by perNyfelt** [comment]
No there is not but it would be pretty easy to add. We can make a global config option to run a script each time the session is (re)started. I imagine it would be 
1. a file called autorun.R in the ride install dir
2. a file called autorun.R in the project dir
So the global option would be 2 checkboxes
"Run autorun.R from Ride install dir each time a session (re)starts."
"Run autorun.R from the project dir (working dir) each time a session (re)starts"

This way you could add global stuff valid for all projects with the first option and project specific ones for the second option.

What do you think?

**Comment by AntoineKMS** [comment]
That sounds exactly like something I want. Especially love having both the global and project specific autorun. 

And Autorun.R would be a simple R program launched at startup ? Like `variable_1 <- TRUE`

**Comment by perNyfelt** [comment]
Yes, exactly. autorun.R would be a simple R program that does whatever you want right after the session has been initialized. You could assign variables like in your example, read a RData file etc. etc.

**Comment by perNyfelt** [comment]
Implemented in version [1.2.9](https://github.com/Alipsa/ride/releases/tag/v1.2.9) that was just released.
